### PR TITLE
operator instana-agent-operator-rhmp (v2.0.30)

### PR DESCRIPTION
**Pull request by Milica-Cvrkota-IBM**

### CODE REVIEW

**Comment by Milica-Cvrkota-IBM** [comment]
Hi @tomasbakk , how can we deal with future PRs? How could we set the label `tests/skip/check_operator_name`? Seems that we currently don't have the right permissions. As this is an issue that will not go away for us, is it possible to have this label added automatically for all `instana-agent-operator-rhmp`? FYI @konrad-ohms

**Comment by tomasbakk** [comment]
> Hi @tomasbakk , how can we deal with future PRs? How could we set the label `tests/skip/check_operator_name`? Seems that we currently don't have the right permissions. As this is an issue that will not go away for us, is it possible to have this label added automatically for all `instana-agent-operator-rhmp`? FYI @konrad-ohms

Hi @Milica-Cvrkota-IBM I added the skip label so the PR can be merged without raising the errors during static_tests. Currently we are working on the bugfix so the label would not be necessary for the future PRs. Fix can be up for a review tomorrow-ish and once deployed, subsequent new bundles should pass without any issues. 
However if there are any other affected PRs, please let me know and I can fix them with the label so you are not blocked by it.

**Comment by Milica-Cvrkota-IBM** [comment]
Sounds great, thanks a lot @tomasbakk ! Here is another PR with the same issue: https://github.com/redhat-openshift-ecosystem/redhat-marketplace-operators/pull/774

**Comment by tomasbakk** [comment]
@Milica-Cvrkota-IBM Once the release pipeline passes for this bundle I will re-trigger the #774 with skip label :+1:

**Pull request merged**
