### PR TITLE
operator flux (0.38.3)

### PR DESCRIPTION
**Pull request by paulofrazao**

### CODE REVIEW

**Comment by acornett21** [comment]
@paulofrazao What versions of OpenShift are you trying to target with this PR? The first time this was open it was 4.8-4.12, now it is 4.6-4.10? Yet the previous version was 4.8-4.11.

**Comment by paulofrazao** [comment]
I tried a combination of different versions to see if this would make any diiference.  I just set it back to v4.8-v4.11, which is the same as v0.36.0.

**Comment by acornett21** [comment]
Is the goal to get this in the 4.12 catalog though?

**Comment by paulofrazao** [comment]
I updated annoations.yaml to:

`com.redhat.openshift.versions: v4.8-v4.12`

**Comment by acornett21** [comment]
@paulofrazao It seems that one of the controllers does not work. Please see the log below

```
oc logs -f notification-controller-5bb4cd67c4-g4r55 
{"level":"info","ts":"2023-02-03T17:07:40.338Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"error","ts":"2023-02-03T17:07:40.352Z","logger":"setup","msg":"unable to create controller","controller":"Alert","error":"no matches for kind \"Alert\" in version \"notification.toolkit.fluxcd.io/v1beta2\""}
```

**Comment by acornett21** [comment]
This bundle only contains an `Alert` CRD for `v1beta1`, not for `v1beta2`, is the CRD incorrect, or is the controller incorrect?

**Comment by paulofrazao** [comment]
Let me speak with Engineering and get back to you.

**Comment by paulofrazao** [comment]
going to redo some changes in next release (v0.39.xx)

**Pull request closed without merging**
